### ISSUE TITLE
Handle dark mode

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/ousd.com#44]
On MacOS Monterey, and likely others, some of the blog post text is not displayed properly when dark mode is activated.

Example: https://www.ousd.com/defi-glossary-of-terms

![dark1](https://user-images.githubusercontent.com/273937/210953879-6d59bead-2611-4991-ba1f-a48527ba18aa.png)

![dark2](https://user-images.githubusercontent.com/273937/210953884-5a1e181b-5a17-40bd-a55e-5e3bbee0f249.jpg)

**Comment by rolandpo** [comment]
This happens when content is copied over to the CMS from some other source together with some formatting. For the record, one should `Remove Format` on the text so that Matt's design styling gets picked up, with the right color scheme for the given website. Otherwise, the style will be overwritten by what's set in the editor (e.g. `Black` font will be black everywhere, `No Color` will be black on website, white on ousd)

I edited the article above the display correctly, can go through some others if they also have the issue

**Comment by rolandpo** [comment]
closing for now
