### ISSUE TITLE
ousd.com SEO optimization

### ISSUE THREAD

**Issue by franckc** [OriginProtocol/ousd.com#50]
- [x] `<H1 class>` Tag on homepage isn’t being picked up as an H1 tag by google. Let’s replace to a regular `<H1>`
 - [ ] ~~Homepage has low text to code ratio, which is typical of thin affiliate LPs. Let's add a section for a block of text at the bottom of the page.~~ Moved to https://github.com/OriginProtocol/ousd.com/issues/87 😐

**Comment by micahalcorn** [comment]
Before we add a text block at the bottom, I'd like to understand how much text we need. https://github.com/OriginProtocol/ousd.com/issues/48 is going to add over 150 words and there's more opportunity to add meaningful content instead of just putting filler at the bottom. I'll check in with the marketing team on this.

**Comment by franckc** [comment]
Updated SEO report: https://docs.google.com/document/d/1lGCvVk3ar6Id-cP0pSTcT20J6FU34z3OT4vUKbvA-lU/edit#

Speed and Content are the high priority items.

**Comment by franckc** [comment]
Closing and will open more specific issue.
